version: '2'
services:
  app:
    build:
      context: ./app
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - ../../:/var/www/html
    networks:
     - vessel
  node:
    build:
      context: ./node
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - ../../:/var/www/html
    networks:
     - vessel
  pgsql:
    image: postgres:11-alpine
    ports:
    - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: "eve_commander"
      POSTGRES_USER: "homestead"
      POSTGRES_PASSWORD: "secret"
    volumes:
    - vesselpgsql:/var/lib/postgresql/data
    networks:
    - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
  echo:
    image: lagun4ik/laravel-echo-server
    ports:
    - "1194:1194/udp"
    restart: always
    volumes:
    - ./echo/laravel-echo-server.json:/app/laravel-echo-server.json
    networks:
    - vessel
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselpgsql:
    driver: "local"
  vesselredis:
    driver: "local"
