sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - PGPORT=5433

services:
  - docker
  - redis-server

addons:
  postgresql: "10"
  apt:
    packages:
     - postgresql-10
     - postgresql-client-10

language: php

php:
  - "7.2"
  - "7.3"

before_script:
  - composer install --optimize-autoloader
  - cp .env.example .env
  - php artisan key:generate
  - php artisan jwt:secret
  - psql -c "CREATE USER commander PASSWORD 'secret';"
  - psql -c "CREATE DATABASE eve_commander WITH OWNER = commander;"
  - psql -c "CREATE DATABASE eve_sde WITH OWNER = commander;"
  - php artisan migrate --seed

script:
  - phpunit

after_success:
  - rm .env
  # PHP-FPM container image
  - export REPO=$DOCKER_USERNAME/evecommander-php;
  - docker build -t $REPO:$COMMIT -f ./docker/production/php/ .;
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BRANCH-latest;
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
  # Nginx image
  - export NGINX_REPO=$DOCKER_USERNAME/evecommander-nginx;
  - docker build -t $NGINX_REPO:$COMMIT -f ./docker/production/nginx/ .;
  - docker tag $NGINX_REPO:$COMMIT $NGINX_REPO:$TRAVIS_BRANCH-latest;
  - docker tag $NGINX_REPO:$COMMIT $NGINX_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop|staging$