sudo: required

services:
  - docker

language: php

php:
  - "7.2"
  - "7.1"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - composer install --optimize-autoloader
  - php artisan config:cache

after_success:
  - rm .env
  - export REPO=$DOCKER_USERNAME/evecommander-php;
  - docker build -t $REPO:$COMMIT .;
  - docker tag $REPO:$COMMIT $REPO:latest;
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER;

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master