sudo: required

services:
  - docker
  - redis-server

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

language: php

php:
  - "7.2"
  - "7.1"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - PGPORT=5433

before_script:
  - composer install --optimize-autoloader
  - cp .env.example .env
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan config:cache
  - php artisan route:cache
  - psql -c 'create database eve_commander;' -u postgres
  - psql -c 'create database eve_sde;' -u postgres
  - php artisan migrate --seed

script:
  - phpunit

after_success:
  - rm .env
  - export REPO=$DOCKER_USERNAME/evecommander-php;
  - docker build -t $REPO:$COMMIT .;
  - docker tag $REPO:$COMMIT $REPO:latest;
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER;

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master