version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
    links:
     - pgsql
     - redis
  pgsql:
    image: postgres:alpine
    ports:
     - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_DATABASE: "eve_commander"
      POSTGRES_USERNAME: "homestead"
      POSTGRES_PASSWORD: "secret"
    volumes:
     - vesselpgsql:/var/lib/postgresql/data
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
  echo:
    image: lagun4ik/laravel-echo-server
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./docker/echo/laravel-echo-server.json:/app/laravel-echo-server.json
    networks:
     - vessel
    links:
      - app
      - redis
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselpgsql:
    driver: "local"
  vesselredis:
    driver: "local"
