version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  pgsql:
    image: postgres:alpine
    ports:
     - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_DATABASE: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
     - vesselpgsql:/var/lib/postgresql/data
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
  echo:
    image: lagun4ik/laravel-echo-server
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - vesselecho:/app
    networks:
     - vessel
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselpgsql:
    driver: "local"
  vesselredis:
    driver: "local"
  vesselecho:
    driver: "local"
